ext {
    androidVersion = [
            applicationId            : 'com.reject.dusty.channel',
            compileSdkVersion        : 32,
            buildToolsVersion        : '32.0.0',
            minSdkVersion            : 26,
            versionCode              : 1,
            versionName              : '1.0.0',
            testInstrumentationRunner: "androidx.test.runner.AndroidJUnitRunner"
    ]

    androidX = [
            appcompat: 'androidx.appcompat:appcompat:1.2.0',
            material : 'com.google.android.material:material:1.4.0',
            junit    : 'junit:junit:',
            extjunit : 'androidx.test.ext:junit:1.1.5',
            espresso : 'androidx.test.espresso:espresso-core:3.5.1'
    ]

    api = [
            okhttp            : 'com.squareup.okhttp3:okhttp:4.9.1',
            retrofitGson      : 'com.squareup.retrofit2:converter-gson:2.5.0',
            rxjava            : 'io.reactivex.rxjava2:rxjava:2.2.20',
            rxAndroid         : 'io.reactivex.rxjava2:rxandroid:2.1.1',
            retrofit          : 'com.squareup.retrofit2:retrofit:2.5.0',
            retrofitAdapter   : 'com.squareup.retrofit2:adapter-rxjava2:2.5.0',
            // glide 图片加载框架
            glide             : 'com.github.bumptech.glide:glide:4.12.0',
            // fastJson json解析 阿里出品
            fastJson          : 'com.alibaba:fastjson:1.2.56',
            // SmartRefreshLayout 加载/刷新框架
            smartRefreshLayout: 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.3',
            // RxBinding 防抖动
            rxbinding         : 'com.jakewharton.rxbinding2:rxbinding:2.2.0',
            statelayout       : 'io.github.shenzhen2017:compose-statelayout:1.0.0',
            // 权限请求框架：https://github.com/getActivity/XXPermissions
            xxPermissions     : 'com.github.getActivity:XXPermissions:12.6',
            // viewModel 绑定依赖
            lifecycle         : 'android.arch.lifecycle:extensions:1.1.1',
            // LiveEventBus
            liveEvent         : 'com.jeremyliao:live-event-bus-x:1.7.2',
            // 主要用于X5WebView
            tencent           : 'com.tencent.tbs.tbssdk:sdk:43967',
            // 沉浸式  详情可参考: https://www.jianshu.com/p/98c1aba92468
            immersionbar      : 'com.gyf.immersionbar:immersionbar:3.0.0',
    ]

    signingKey = [
            storeFile    : 'keystore/app.jks',
            keyAlias     : 'Preter ici',
            keyPassword  : 'Preter ici',
            storePassword: 'Preter ici',
    ]
}